update postfix
Signed-off-by: Jess Frazelle <acidburn@microsoft.com>

diff --git a/postfix/service/postfix/run b/postfix/service/postfix/run
--- a/postfix/service/postfix/run
+++ b/postfix/service/postfix/run
@@ -80,4 +80,17 @@ if [[ ! -z "$SASL_AUTH" ]]; then
 	chmod 600 /etc/postfix/sasl_passwd.db
 fi
 
-/usr/lib/postfix/master -c /etc/postfix -d 2>&1
+if [[ -f "/usr/libexec/postfix/master" ]]; then
+	cmd="/usr/libexec/postfix/master"
+fi
+
+if [[ -f "/usr/lib/postfix/master" ]]; then
+	cmd="/usr/lib/postfix/master"
+fi
+
+if [[ -z "$cmd" ]]; then
+	echo "Could not find postfix master in /usr/lib or /usr/libexec"
+	exit 1
+fi
+
+"$cmd" -c /etc/postfix -d 2>&1
